#!/usr/share/ucs-test/runner python3
## desc: Create users/user with uidNumber which is already in use
## tags: [udm,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools

import sys
import random
import univention.testing.utils as utils
import univention.testing.udm as udm_test


if __name__ == '__main__':
	uid_number = str(random.randint(3000, 4999))
	with udm_test.UCSTestUDM() as udm:
		udm.create_user(uidNumber=uid_number)
		try:
			udm.create_user(uidNumber=uid_number)
		except udm_test.UCSTestUDM_CreateUDMObjectFailed:
			sys.exit(0)

	utils.fail('Successfully created a user with an "uidNumber" which is already in use, which should not be possible')
